name: reachout
description: Expert consultation application
publish_to: 'none'

version: 1.4.2+13
environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  carousel_slider: ^4.2.1
  dio: ^5.1.2
  firebase_core: ^2.17.0
  flutter_animator: ^3.2.2
  flutter_form_builder: ^9.0.0
  flutter_native_splash: ^2.3.0
  flutter_riverpod: ^2.3.6
  flutter_share: ^2.0.0
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.6
  form_builder_validators: ^9.0.0
  freezed_annotation: ^2.2.0
  get_it: ^7.6.0
  google_fonts: ^4.0.4
  google_sign_in: ^6.1.0
  iconsax: ^0.0.8
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  package_info_plus: ^3.1.2
  shared_preferences: ^2.1.1
  shimmer: ^3.0.0
  url_launcher: ^6.1.11


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.4
  flutter_lints: ^2.0.0
  freezed: ^2.3.4
  json_serializable: ^6.7.0


flutter:
  uses-material-design: true

  assets:
    - assets/ca/
    - assets/icons/
    - assets/images/


flutter_native_splash:
  color: "#ffffff"
  image: assets/images/app-logo.png

flutter_launcher_icons:
  android: "ic_launcher"
  ios: false
  image_path: "assets/images/img-logo.png"
  min_sdk_android: 21